### PR TITLE
Multiple fixes for path-related issues and other stuff...

### LINKED ISSUE #1410: VIPS-WARNING: unable to load vips-magick.dll, vips-openslide.dll, vips-poppler.dll on Windows despite files being present
**Description**

When running LANraragi 0.9.6 on Windows, the application functions normally but generates VIPS warnings in the logs indicating that it cannot load several VIPS modules, even though the DLL files are present in the correct directory.

**Error Log**

Minion will use the Redis database at 127.0.0.1:6379/1
[LANraragi] [info] Successfully connected to Minion database.
[Minion] [info] Starting new Minion worker with PID 22640.
[LANraragi] [info] Routing done! Ready to receive requests.

(process:9612): VIPS-WARNING **: 22:51:17.689: unable to load "D:\Programs\LANraragi\lanraragi\runtime/lib/vips-modules-8.17\vips-magick.dll" -- 'D:\Programs\LANraragi\lanraragi\runtime/lib/vips-modules-8.17\vips-magick.dll': 找不到指定的模块。

(process:9612): VIPS-WARNING **: 22:51:17.692: unable to load "D:\Programs\LANraragi\lanraragi\runtime/lib/vips-modules-8.17\vips-openslide.dll" -- 'D:\Programs\LANraragi\lanraragi\runtime/lib/vips-modules-8.17\vips-openslide.dll': 找不到指定的模块。

(process:9612): VIPS-WARNING **: 22:51:17.694: unable to load "D:\Programs\LANraragi\lanraragi\runtime/lib/vips-modules-8.17\vips-poppler.dll" -- 'D:\Programs\LANraragi\lanraragi\runtime/lib/vips-modules-8.17\vips-poppler.dll': 找不到指定的模块。
[2025-11-15 22:51:17.75647] [9612] [info] Listening at "http://*:13000"
Web application available at http://127.0.0.1:13000

**Environment**

OS: Windows 11
LANraragi Version: 0.9.6 (upgraded from 0.9.5)
Upgrade Method: In-place file replacement/overwrite

**Steps to Reproduce**

Upgrade LANraragi from version 0.9.5 to 0.9.6 on Windows
Check the application logs
Observe VIPS warnings for missing module errors

**What I've Tried**

Verified that the DLL files exist in the specified directory
Attempted to manually download and replace VIPS runtime files
The application appears to function normally despite the warnings

### LINKED ISSUE #1418: Upload: overly long filename cause filename cutted
**LRR Version and OS**
LRR: 0.9.6 
OS: Windows11 25H2(26200.7171) ProWorkstation
Install: MSI

**Bug Details**
When uploading a file which filename is long, LRR shows `Unsupported File Extension` err, and the filename on the left shows this overly long filename has been cutted.
- LRR install path: `D:\LANraragi`
- Content Folder Location: `H:\MangaLibrary`

**Matching Logs**
[lanraragi.log](https://github.com/user-attachments/files/23748772/lanraragi.log)

**Screenshots**
Image

### PR DESCRIPTION
**Pull request by Guerra24**
- Fix #1410.
- Fix #1418.
- Fix filewatcher delete event using short paths instead of long paths.
- Added get_archive_path for getting the archive path without going through create_path every time.
- Better handling of special characters when uploading files.
- Install windows deps as part of the MSYS2 setup step.
- Update perl deps on Windows.
- Bump Alien::FFI version.

[Win32::FileSystemHelper diff](https://github.com/Guerra24/Win32-FileSystemHelper/commit/308b92c958bb4931dfd704cc5025f93e28ef0c8a)

### CODE REVIEW

File: lib/LANraragi/Model/Upload.pm [hunk 1]
```diff
@@ -85,7 +85,7 @@ sub handle_incoming_file ( $tempfile, $catid, $tags, $title, $summary ) {
 
     # Add the file to the database ourselves so Shinobu doesn't do it
     # This allows autoplugin to be ran ASAP.
-    my $name = add_archive_to_redis( $id, $output_file, $redis, $redis_search );
+    my $name = add_archive_to_redis( $id, redis_encode( redis_decode( $output_file ) ), $redis, $redis_search );
```
Comment (Difegue) [inline lib/LANraragi/Model/Upload.pm]: I'm quite wary of this PR making changes to effectively store encoded filenames in Redis instead of raw bytes from the FS - Historically not using the exact filepaths the host filesystem caused a ton of issues on systems with weird locales.

File: lib/LANraragi/Controller/Upload.pm [hunk 2]
```diff
@@ -37,18 +38,11 @@ sub process_upload {
...
-        find(
-            sub {
-                return if -d $_;
-                $tempfile = $File::Find::name;
-                $filename = $_;
-            },
-            $tempdir
-        );
+
+        my $mojo_temp = tmpnam(); # Create another temp file as a target for Mojo's move_to so that the original handle can be closed
```
Comment (Difegue) [inline lib/LANraragi/Controller/Upload.pm]: At a glance I'm not sure which problem this solves so it probably at least needs more commenting 🤔  

What does the original handle mentioned here belong to -- The mojo `$file`?

**Review by Difegue — CHANGES_REQUESTED** [review]

File: lib/LANraragi/Controller/Upload.pm (hunk 2 above)
Comment (Guerra24) [reply lib/LANraragi/Controller/Upload.pm]: I will add them but the tl;dr is that mojo holds an open handle to the file blocking it from being moved on Windows. Yes, the $file object holds it.

**Comment by Guerra24** [comment]
Current state of the encoding issues in this pr:

Linux has working encoding in both api and web uploads, both match and behave the same during testing.

Windows has working encoding for web uploads. The api will process the files in the wrong encoding, but when they are moved into the content folder Shinobu automatically fixes the paths to the correct fs encoding. ID generation is not affected by the encoding and file operations continue to work.

I don't have leads or ideas or anything that could explain said behavior, I literally have no idea what the hell is going on. Previous to this I did not test the upload api so for all I know it might be completely broken in prod on Windows (Not that anyone is using it).

Up to you dfug if you want me to keep or remove the encoding changes.

**Comment by Difegue** [comment]
Given the test results I think this will work out ok for 95% of setups, and has the perk of cleaning up the old minion jank -- Let's try it out and see how it goes.
